swagger: "2.0"


info:
  description: "Hypermedia project by Roccamena, Romanò, Buttolo"
  version: "1.0.0"
  title: "Child4Help"
  termsOfService: "http://swagger.io/terms/"
  
  
tags:
- name: "service"
  description: "Services provided"
- name: "event"
  description: "Events organized"
- name: "person"
  description: "People involved"
- name: "article"
  description: "Articles about the association"
- name: "contact"
  description: "Contacts of the association"


paths:
  /service:
    get:
      tags:
      - "service"
      summary: "Get all services"
      operationId: "getServiceAll"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Service"
  /service/{id_service}:
    get:
      tags:
      - "service"
      summary: "Get a service by ID"
      operationId: "getServiceByID"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id_service"
        in: "path"
        description: "ID of service to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Service"
        "400":
          description: "invalid ID supplied"
        "404":
          description: "service not found"


definitions:
  Service:
    type: "object"
    required:
    - "id_service"
    - "name"
    properties:
      id_service:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      presentation:
        type: "string"
      informations:
        type: "string"
      location:
        type: "string"
      photo_url:
        type: "string"
    xml:
      name: "Service"
      
  Event:
    type: "object"
    required:
    - "id_event"
    - "id_person"
    - "name"
    properties:
      id_event:
        type: "integer"
        format: "int64"
      id_person:
        $ref: "#/definitions/Person"
      name:
        type: "string"
      date:
        type: "string"
        format: "date"
      location:
        type: "string"
      description:
        type: "string"
      pract_info:
        type: "string"
      photo_url:
        type: "string"
    xml:
      name: "Event"
      
  Person:
    type: "object"
    required:
    - "id_person"
    - "name"
    - "email_address"
    - "phone_number"
    properties:
      id_person:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      role:
        type: "string"
      email_address:
        type: "string"
        format: "email"
      phone_number:
        type: "string"
      description:
        type: "string"
      photo_url:
        type: "string"
      starting_date:
        type: "string"
        format: "date"
    xml:
      name: "Person"
    
  Article:
    type: "object"
    required:
    - "id_article"
    - "title"
    - "body"
    properties:
      id_article:
        type: "integer"
        format: "int64"
      id_service:
        $ref: "#/definitions/Service"
      id_event:
        $ref: "#/definitions/Event"
      author:
        type: "string"
      publication_date:
        type: "string"
        format: "date"
      email_address:
        type: "string"
        format: "email"
      title:
        type: "string"
      body:
        type: "string"
      photo_url:
        type: "string"
    xml:
      name: "Article"
      
  Contact:
    type: "object"
    required:
    - "id_contact"
    - "email_address"
    properties:
      id_contact:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      phone:
        type: "string"
        format: "date"
      email_address:
        type: "string"
        format: "email"
      location:
        type: "string"
    xml:
      name: "Contact"